/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        cream: { DEFAULT: '#F5EFE0', light: '#FAFAF7', dark: '#EDE0C8' },
        brown: { DEFAULT: '#8B6347', deep: '#3D2314' },
        gold: '#C9A96E',
        "secondary-fixed": "#ffdea4",
        "on-primary-fixed-variant": "#613f26",
        "surface": "#f9f9f6",
        "on-tertiary": "#ffffff",
        "secondary": "#745a27",
        "tertiary-container": "#876451",
        "surface-container": "#eeeeeb",
        "secondary-container": "#fedb9b",
        "inverse-primary": "#eebc9b",
        "on-secondary-fixed-variant": "#5a4312",
        "on-tertiary-fixed": "#2d1608",
        "on-surface-variant": "#50443d",
        "inverse-on-surface": "#f1f1ee",
        "background": "#f9f9f6",
        "outline-variant": "#d4c3b9",
        "on-error": "#ffffff",
        "on-tertiary-container": "#ffeae0",
        "inverse-surface": "#2f312f",
        "primary-container": "#8b6347",
        "primary-fixed": "#ffdcc6",
        "on-secondary-container": "#795f2b",
        "error": "#ba1a1a",
        "surface-dim": "#dadad7",
        "surface-container-highest": "#e2e3e0",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1a1c1b",
        "primary": "#704b31",
        "on-secondary-fixed": "#261900",
        "error-container": "#ffdad6",
        "surface-tint": "#7c563b",
        "surface-container-low": "#f4f4f1",
        "on-error-container": "#93000a",
        "surface-container-high": "#e8e8e5",
        "tertiary-fixed": "#ffdbca",
        "tertiary-fixed-dim": "#e9bda7",
        "on-tertiary-fixed-variant": "#5e402f",
        "surface-variant": "#e2e3e0",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#2f1502",
        "outline": "#82746c",
        "on-primary-container": "#ffeade",
        "primary-fixed-dim": "#eebc9b",
        "surface-bright": "#f9f9f6",
        "tertiary": "#6c4c3b",
        "secondary-fixed-dim": "#e4c285",
        "on-surface": "#1a1c1b"
      },
      fontFamily: {
        serif: ['Times New Roman', 'Playfair Display', 'serif'],
        sans: ['Cormorant Garamond', 'sans-serif'],
        "display-lg": ["EB Garamond", "serif"],
        "quote": ["EB Garamond", "serif"],
        "headline-lg-italic": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "body-lg": ["EB Garamond", "serif"],
        "body-md": ["EB Garamond", "serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      letterSpacing: {
        editorial: '0.15em',
        wide: '0.08em'
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "24px",
        "margin-desktop": "80px",
        "hairline": "1px",
        "section-gap": "160px",
        "gutter": "32px"
      },
      fontSize: {
        "display-lg": ["80px", {"lineHeight": "88px", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "quote": ["24px", {"lineHeight": "36px", "fontWeight": "400"}],
        "headline-lg-italic": ["40px", {"lineHeight": "48px", "fontWeight": "400"}],
        "headline-lg": ["40px", {"lineHeight": "48px", "fontWeight": "400"}],
        "display-lg-mobile": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "body-lg": ["20px", {"lineHeight": "32px", "fontWeight": "400"}],
        "body-md": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "300"}]
      }
    },
  },
  plugins: [],
};
